---
- name: Update repositories
  apt:
    update_cache: yes
  become: true

- name: apt-get install packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
  - rxvt-unicode
  - xfonts-terminus
  - tmux
  - emacs
  - rsync
  become: true
